# Generated by Django 2.0.6 on 2018-06-15 03:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('residents', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street', models.CharField(max_length=200)),
                ('baranggay', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=200)),
            ],
        ),
        migrations.RemoveField(
            model_name='resident',
            name='brgy',
        ),
        migrations.RemoveField(
            model_name='resident',
            name='city',
        ),
        migrations.AddField(
            model_name='resident',
            name='address',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='residents.Address'),
        ),
    ]
