# Generated by Django 2.0.6 on 2018-06-15 06:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('residents', '0002_auto_20180615_1116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resident',
            name='address',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='residents.Address'),
        ),
    ]
