# Generated by Django 2.0.6 on 2018-06-15 06:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('residents', '0003_auto_20180615_1423'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resident',
            name='address',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='residents.Address'),
        ),
    ]
